### ISSUE TITLE
ascii_cmp reads bits in reverse order

### ISSUE THREAD

**Issue by mmalvarez** [coq-ext-lib/coq-ext-lib#13]
in [String.v](https://github.com/coq-ext-lib/coq-ext-lib/blob/9d7c7449778ecb8111c0765c542eb5feba4ce2c2/theories/Data/String.v#L25), the function ascii_cmp gives in correct results. For instance it says "a" > "b" but "b" < "c".

This appears to be because it is reading bits from the ASCII representation in the reverse order. The representation stores the least-significant bit first, but ascii_cmp treats the first bit as if it were the most-significant.

**Comment by gmalecha** [comment]
Fixed in 876e099

**Comment by gmalecha** [comment]
Fixed in 8.4 2caa401
