### ISSUE TITLE
Breaking changes in Coq 8.5~beta3

### ISSUE THREAD

**Issue by clarus** [coq-ext-lib/coq-ext-lib#14]
The package [coq:ext-lib.1.0.0~beta2](http://coq.io/opam/coq:ext-lib.1.0.0~beta2.html) does not compile anymore with Coq 8.5~beta3. See [bench error](https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/released/8.5~beta3/ext-lib/1.0.0~beta2.html). I updated the dependencies in [ebb5b6b830a0addb21b9c2ad4f5afd98cf12d9e6](https://github.com/coq/opam-coq-archive/commit/ebb5b6b830a0addb21b9c2ad4f5afd98cf12d9e6).

**Comment by gmalecha** [comment]
Thanks.

There isn't an official beta3 tarball yet. Do I just build it against the 8.5 branch to see these errors?

**Comment by clarus** [comment]
The website of Coq is not updated yet, but there is an OPAM package `coq.8.5~beta3` (in the `released` repository, will soon be moved to `core-dev`). The tarballs will arrive by a few days, I guess. Else the 8.5 branch should be pretty close to the beta3.

**Comment by gmalecha** [comment]
This is fixed now with a new release.
