### ISSUE TITLE
new 0.9.X release to update OPAM package

### ISSUE THREAD

**Issue by vzaliva** [coq-ext-lib/coq-ext-lib#18]
With recent patches to v8.4 branch we fixed build under MacOS. Now we need to update OPAM package in Coq OPAM repository. For this I need to have a new released version of ExtLib to build from. 

Current OPAM package is referencing https://github.com/coq-ext-lib/coq-ext-lib/archive/v0.9.0.tar.gz
Perhaps you can release 0.9.1?  I will be glad to submit an update to Coq OPAM package.

**Comment by gmalecha** [comment]
I just made a 0.8.0 release for 8.4. It is a different feature set from 0.9.0 so it has a different minor version number.

**Comment by vzaliva** [comment]
What about 0.9.0 which is currently in OPAM? Should we update it to compile on Mac?
Alternatively I can submit an additional package for 0.8.0 which looks like a downgrade...

**Comment by vzaliva** [comment]
https://github.com/coq-ext-lib/coq-ext-lib/archive/v0.8.0.tar.gz does not work. I need download URL to build OPAM package.

**Comment by vzaliva** [comment]
I have submitted new package version to OPAM https://github.com/coq/opam-coq-archive/pull/43

**Comment by gmalecha** [comment]
I'm not sure if I just clobbered this release. Does it still work?

**Comment by vzaliva** [comment]
0.9.1 just made into official OPAM repo and now generally available. Thanks!

**Comment by gmalecha** [comment]
Thanks so much!
