### ISSUE TITLE
Shadow PositiveMap.t

### ISSUE THREAD

**Issue by braibant** [coq-ext-lib/coq-ext-lib#2]
When compiling ppsimpl (a new package for Coq's opam), I realized that it seems that coq_extlib conflicts with it because it shawos PositiveMap.t somehow. I feel that it is related to the "-R" problem discussed on Coq's mailing list, but I would be glad if you could just confirm this.

**Comment by gmalecha** [comment]
This is the same as #9 it is solved in 8.5
