### ISSUE TITLE
WriterMonad

### ISSUE THREAD

**Issue by vzaliva** [coq-ext-lib/coq-ext-lib#21]
Any reason that there is only transformer version ``WriterMonadT``? Why there is no stand-alone version like you have for ``StateMonad``?

**Comment by gmalecha** [comment]
It might be good to add one for convenience. But it can be derived directly from WriterT and Identity. In the future when we have interesting reasoning, we will likely only want the transformers so that we can avoid proving so much.

**Comment by gmalecha** [comment]
I'm going to mark this as 'wontfix' for the time being. If you think things would be better with a stand-alone writer monad, please submit a pull request.

**Comment by vzaliva** [comment]
I am not sure if this is the best way to implement this, but I am using this simple wrapper:

```
Section WriterMonad.
  Variable s t : Type.
  Variable Monoid_s : Monoid s.
  
  Definition writer := writerT Monoid_s ident.
  Definition runWriter x := unIdent (@runWriterT s Monoid_s ident t x).
  Definition execWriter x:= snd (runWriter x).
  Definition evalWriter x:= fst (runWriter x).
End WriterMonad.

```

If that is useful I can do a pull request for this definition along with simple example. However it might be to trivial to add.
