### ISSUE TITLE
Compilation broken in git branch v8.5

### ISSUE THREAD

**Issue by ejgallego** [coq-ext-lib/coq-ext-lib#22]
Hi Gregory,

coq-ext-lib compilation is broken in the v8.5 branch by this patch:
https://github.com/coq/coq/commit/b582db2ecbb3f7f1315fedc50b0009f62f5c59ad

The error message I get is:
```
"coqc"  -q  -Q "theories" ExtLib   theories/Core/Type
File "./theories/Core/Type.v", line 27, characters 2-23:
Error: Cannot mix universe polymorphic and monomorphic declarations in sections.
Makefile.coq:358: recipe for target 'theories/Core/Type.vo' failed
```

**Comment by gmalecha** [comment]
Fixed in: 5541581

**Comment by ejgallego** [comment]
Thanks! If you are interested jsCoq ships MirrorCore now, you can try it at:
https://x80.org/rhino-coq/examples/mirrorcore.html

**Comment by gmalecha** [comment]
This is cool. I tried out the demo but I got an anomaly when running

    Eval vm_compute in 1 + 2.

MirrorCore makes heavy use of ```vm_compute``` to make reduction fast, does it work in jsCoq?

A better example might be the setoid demo https://github.com/gmalecha/mirror-core/blob/master/examples/Cancel/RtacDemo.v which actually uses a reflective procedure implemented in Rtac.

**Comment by ejgallego** [comment]
Most uses cases for jsCoq (documentation, tutorials) don't need `vm_compute` so unfortunately it is not ported yet as it depends on C code. We could however port it if there's a need.

The example is noted thanks! Actually we generate pages from CoqDoc scripts so even the docs could be runnable.

**Comment by ejgallego** [comment]
`RtacDemo.v` added at https://x80.org/rhino-coq/examples/mirror-core-rtac-demo.html.

Unfortunately until we don't port `vm_compute` indeed the tactic is quite slow.
