### ISSUE TITLE
coqdoc

### ISSUE THREAD

**Issue by aa755** [coq-ext-lib/coq-ext-lib#24]
Is there some website that publicly hosts the coqdoc (html) for coq-ext-lib?

**Comment by gmalecha** [comment]
Currently no. You wouldn't happen to have a script that builds it in a suitable way to publish as a github pages would you?

**Comment by aa755** [comment]
I use CoRN/math-classes' scons scripts to build coqdoc (and .vo files as well). Those scripts find out all the .v files, including those in the non-std-lib dependencies, and invoke coqdoc on the entire collection at once -- this is necessary for cross-linking between files and libraries. 
Because coq-ext-lib does not use have any non-std-lib dependencies, you can build coqdoc using
`coqdoc -utf8 --toc --interpolate --no-lib-name --coqlib http://coq.inria.fr/library -d coqdoc -R theories Extlib [all_v_files]`

If you wish to use scons scripts to automate the instantiation of `[all_v_files]`, let me know and I will be happy to submit a pull request.

**Comment by gmalecha** [comment]
A pull request would be great.

**Comment by aa755** [comment]
I noticed that the Makefile generated by Coq already supports coqdoc generation:
`make -f Makefile.coq html`

**Comment by gmalecha** [comment]
Temporary documentation can now be found here http://coq-ext-lib.github.io/coq-ext-lib/

I need to see if there is some way to set up something to auto-generate documentation.
