### ISSUE TITLE
OPAM package lacks source files

### ISSUE THREAD

**Issue by vzaliva** [coq-ext-lib/coq-ext-lib#29]
Version 0.9.4 installed via _opam_ installs only .vo files, but not .v, like other _opam_ library packages do.

It would be convenient to install sources as well as it would allow, for example, to quickly examine definitions pressing **M-.** in _Emacs_.

**Comment by gmalecha** [comment]
Do you know how to change the package to install sources as well? I'd be happy to merge a pull request.

**Comment by vzaliva** [comment]
I quickly took a look and the 'install' target in 'Makefile.coq' generated during ext-lib build, copies .v files. 
I suspect they problem lays somewhere in OPAM packaging.

As starting point, 'coq-color' and 'coq-math-classes' OPAM packages both correctly install .v files.

**Comment by vzaliva** [comment]
Did more digging while waiting for my flight :)
The problem is in coq_makefile. I have opened a bug:

https://coq.inria.fr/bugs/show_bug.cgi?id=5132

**Comment by gmalecha** [comment]
I'm assuming that this is fixed now that this patch got merged.
