### ISSUE TITLE
coq 8.6 support

### ISSUE THREAD

**Issue by vzaliva** [coq-ext-lib/coq-ext-lib#30]
current opam version fails to install with coq-8.6

**Comment by gmalecha** [comment]
Going to start a new branch for this.

**Comment by vzaliva** [comment]
Great! I just did a quick build and it compiles OK. There are few warnings about "Maximum Implicit Arguments" option, but I guess these are not critical. Do you plan to push it to OPAM soon?

Thanks again for your quick response!

**Comment by gmalecha** [comment]
I just opened a PR for opam-coq-archive (https://github.com/coq/opam-coq-archive/pull/125).

**Comment by vzaliva** [comment]
Just FYI, there is a problem installing it via OPAM: https://github.com/coq/opam-coq-archive/issues/126
