### ISSUE TITLE
Operator associativity

### ISSUE THREAD

**Issue by liyishuai** [coq-ext-lib/coq-ext-lib#61]
`<$>` and `<*>` are currently defined as right associative: https://github.com/coq-ext-lib/coq-ext-lib/blob/c0c934cd3c5fe24f55f41981e86a22a77f08f1ff/theories/Structures/Functor.v#L29 https://github.com/coq-ext-lib/coq-ext-lib/blob/c0c934cd3c5fe24f55f41981e86a22a77f08f1ff/theories/Structures/Applicative.v#L16 while they are left associative in Haskell: [`<$>`](//hackage.haskell.org/package/base-4.12.0.0/docs/Data-Functor.html#v:-60--36--62-) [`<*>`](//hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#v:-60--42--62-).
Is it designated on purpose, or is it worth changing them to left associative?

Say that I have: 
```coq
Parameter parser : Type -> Type.
Instance Monad_parser : Monad parser. Admitted.
Parameter A B C D : Type.
Parameter pA : parser A.
Parameter pB : parser B.
Parameter pC : parser C.
Parameter f : A -> B -> C -> D.
```
To write a parser for `D` (without `liftA2`), I need:
```coq
Definition pD : parser D := ((f <$> pA) <*> pB) <*> pC.
```
where the parentheses are not required if the operators were left associative.

**Comment by gmalecha** [comment]
They should be changed. Can you please open a pull request?
