### ISSUE TITLE
Functor and Monad notations conflict

### ISSUE THREAD

**Issue by jbaum98** [coq-ext-lib/coq-ext-lib#66]
Both Functor and Monad notations are declares at level 51, but Functor notation is left associative while Monad notation is right associative. I've solved this locally by changing the Functor notations to level 52, so if that's the right approach I'm happy to submit the tiny PR.

**Comment by gmalecha** [comment]
That is probably the right way to go. There is a convention in Coq to use even and odd numbers for left and right associative entries, but I don't recall which is which. Can you confirm in the standard library and make a PR?

**Comment by jbaum98** [comment]
Based on https://coq.inria.fr/library/Coq.Init.Notations.html, I guess it would be that even is left and odd is right, but this is not such a strict convention (see ^)
```coq
Reserved Notation "x + y" (at level 50, left associativity).
Reserved Notation "x - y" (at level 50, left associativity).
Reserved Notation "x * y" (at level 40, left associativity).
Reserved Notation "x / y" (at level 40, left associativity).
Reserved Notation "- x" (at level 35, right associativity).
Reserved Notation "/ x" (at level 35, right associativity).
Reserved Notation "x ^ y" (at level 30, right associativity).
```

**Comment by gmalecha** [comment]
Alright, let's do that even left, odd right. Can you make a PR?
