### ISSUE TITLE
There is too much shadowing of standard modules

### ISSUE THREAD

**Issue by jwiegley** [coq-ext-lib/coq-ext-lib#9]
Because ext-lib defines modules like Bool, I've found that when you have ext-lib installed globally, it shadows too many of the standard modules for developments which just `Require Bool`.  For example, Software Foundations cannot compile in the presence of coq-ext-lib.  I've run into such discrepancies in other projects as well, where because of the presence of ext-lib (even though I never asked to use ext-lib), it was causing compilation behavior to differ between multiple environments.  Finally I had to uninstall ext-lib just to keep a sane environment.

So my recommendation is to employ some mechanism to avoid shadowing anything that might be implicitly imported from the stdlib, like bools and tuples.

**Comment by gmalecha** [comment]
This is solved in 8.5
